{
  imports = [
    ./edit/blink-pairs.nix
    ./edit/flash.nix
    ./vcs/neogit.nix
    ./apperance/lualine.nix
    ./tools/neotree.nix
    ./apperance/bufferline.nix
    ./apperance/colorful-winsep.nix
    ./apperance/noice.nix
    ./tools/direnv.nix
    ./edit/blink-cmp.nix
    ./misc/cord.nix
    ./edit/img-clip.nix
    ./tools/kitty-scrollback.nix
    ./edit/treesitter-context.nix
    ./edit/treesj.nix
    ./edit/blink-indent.nix
    ./lang/bullets.nix
    ./vcs/codediff.nix
    ./tools/conform.nix
    ./apperance/dropbar.nix
    ./vcs/gitsigns.nix
    ./tools/grug-far.nix
    ./lsp
    ./core
    ./snacks
    ./lang/lazydev.nix
    ./edit/luasnip.nix
    ./edit/multicursors.nix
    ./edit/treesitter-textobjects.nix
    ./edit/treesitter-autotag.nix
    ./edit/treesitter.nix
    ./tools/toggleterm.nix
    ./apperance/todo-comments.nix
    ./tools/trouble.nix
    ./lang/typst-preview.nix
    ./lang/vimtex.nix
    ./tools/sops.nix
    ./tools/limes.nix
  ];
  plugins.lz-n.enable = true;
  colorschemes.kanagawa.enable = true;
}
