{
  imports = [
    ./tools/diagnostic.nix
    ./edit/blink-pairs.nix
    ./appearance/which-key.nix
    ./edit/flash.nix
    ./vcs/neogit.nix
    ./appearance/lualine.nix
    ./tools/neotree.nix
    ./appearance/bufferline.nix
    ./appearance/colorful-winsep.nix
    ./appearance/noice.nix
    ./tools/direnv.nix
    ./edit/blink-cmp.nix
    ./misc/cord.nix
    ./edit/img-clip.nix
    ./tools/kitty-scrollback.nix
    ./edit/treesitter-context.nix
    ./edit/treesj.nix
    ./vcs/codediff.nix
    ./tools/conform
    ./appearance/dropbar.nix
    ./vcs/gitsigns.nix
    ./tools/grug-far.nix
    ./lsp
    ./core
    ./snacks
    ./edit/luasnip.nix
    ./edit/multicursors.nix
    ./edit/treesitter-textobjects.nix
    ./edit/treesitter-autotag.nix
    ./edit/treesitter.nix
    ./appearance/todo-comments.nix
    ./tools/trouble.nix
    ./tools/sops.nix
    ./tools/limes.nix
    ./tools/oil.nix
    ./lang
  ];
  plugins.lz-n.enable = true;
  colorschemes.kanagawa.enable = true;
}
