local M = {
  diagnostics = {
    Error = '',
    Warning = '',
    Hint = '',
    Information = '',
  },
  lsp = '',
  indent = '',
  git = {
    Change = '',
    Add = '',
    Delete = '',
    Rename = '',
    Branch = '',
  },
  lsp_kind = {
    Text = '󰉿',
    Method = '󰆧',
    Function = '󰊕',
    Constructor = '',
    Field = '󰜢',
    Variable = '󰀫',
    Class = '󰠱',
    Interface = '',
    Module = '',
    Property = '󰜢',
    Unit = '󰑭',
    Value = '󰎠',
    Enum = '',
    Keyword = '󰌋',
    Snippet = '',
    Color = '󰏘',
    File = '󰈙',
    Reference = '󰈇',
    Folder = '󰉋',
    EnumMember = '',
    Constant = '󰏿',
    Struct = '󰙅',
    Event = '',
    Operator = '󰆕',
    TypeParameter = '󰅲',
    Copilot = '',
  },
  telescope = ' ',
}

return M
